// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pylarlurrffjenwnnyvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5bGFybHVycmZmamVud25ueXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2NzcwMDQsImV4cCI6MjA5MzI1MzAwNH0.cPJ1qNliPd6hPaA7qfXrbeT-YhgQFgu29JyUBkmqDHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});